# Any key/value defined here can be accessed from any NotArb config (excluding [launcher] config) by using ${KEY} in strings.
#   Example 1: keypair_path="${DEFAULT_KEYPAIR_PATH}"
#   Example 2: jito_uuid="${MY_SECRET_UUID}" (where MY_SECRET_UUID="1415201182" would be defined below)

DEFAULT_KEYPAIR_PATH="/path/to/keypair"
DEFAULT_SENDER_RPC_URL="your.rpc.url"