# Need help with configuration? Check out our complete guide:
# https://github.com/NotArb/Release/tree/main/onchain-bot#readme

[launcher]
task="onchain-bot"
jvm_args=[
    "-server",
    "-Xmx4096m"
]

[notarb]
acknowledge_terms_of_service=false

[user]
keypair_path="${DEFAULT_KEYPAIR_PATH}"
protect_keypair=false

[token_accounts_checker]
rpc_url="${DEFAULT_RPC_URL}"
delay_seconds=3

[blockhash_updater]
rpc_url="${DEFAULT_RPC_URL}"
delay_seconds=3

[account_size_loader]
rpc_url="${DEFAULT_RPC_URL}"
invalid_account_size=200 # the default size to use for invalid accounts (accounts with no data, which can sometimes happen when accounts that don't exist yet)
buffer_size=1500 # how many extra bytes would you like to append to the total size (just a fail-safe type value, can be 0)

[market_loader]
rpc_url="${DEFAULT_RPC_URL}"

[lookup_table_loader]
rpc_url="${DEFAULT_RPC_URL}"

[transaction_executor]
threads=0 # 0 will use a dynamic cached thread pool, -1 will use a thread per task, anything > 0 will use a fixed thread pool

[[spam_rpc]]
id="my-super-duper-sender"
url="${DEFAULT_RPC_URL}"
max_idle_connections=1

[jito]
ips_file_path="" # required for proxy senders (.txt file with 1 ip/proxy per line)
prefunded_keypairs_path="" # optional - only for proxy senders (.txt file with 1 keypair per line)

[[jito.rpc]]
enabled=true
id="jito-1"
uuid="" # leave empty if you have none - use cautiously, sends are not automatically rate limited like the jupiter bot
regions=["ny", "slc", "london", "frankfurt", "amsterdam", "tokyo"] # each region will be sent to concurrently

[[jito.rpc_proxy]]
enabled=false
id="jito-2"
regions=["ny", "slc", "london", "frankfurt", "amsterdam", "tokyo"]

[[markets_file]]
enabled=true
path="markets.toml" # also supports json, but must be a 2d array of market addresses
update_seconds=3

[[markets_url]]
enabled=false
url="https://notarb.org/markets.json" # also supports json, but must be a 2d array of market addresses
update_seconds=3

[[lookup_tables_file]]
enabled=true
path="lookup-tables.txt" # also supports json, but must be 1d array of market addresses
update_seconds=3

[[lookup_tables_url]]
enabled=false
path="https://notarb.org/lups.json" # also supports json, but must be 1d array of market addresses
update_seconds=3


## SOL (Jito)
[[swap]]
enabled=true
mint="SOL"

[swap.strategy_defaults]
meteora_bin_limit=20 # default 20 - helps keep cu down on high liquidity markets

[[swap.strategy]]
cu_limit=369_369
min_jito_tip_lamports=1000
max_jito_tip_lamports=1000
prefer_success=false # warning: setting this to true will land txs any pay Jito tips even if there's no arbitrage opportunity.
cooldown_ms=1337
#exclude_jito_senders=["jito-2"] # optionally exclude specific jito senders


## SOL (Spam)
[[swap]]
enabled=true
mint="SOL"

[swap.strategy_defaults]
meteora_bin_limit=20 # default 20 - helps keep cu down on high liquidity markets

[[swap.strategy]]
cu_limit=369_369
min_priority_fee_lamports=1900
max_priority_fee_lamports=6900
spam_senders=[
    { rpc="my-super-duper-sender", skip_preflight=true, max_retries=0 },
]
cooldown_ms=369