[launcher]
task="create-lookup-table"
jvm_args=["-Xmx512m"]

[config]
keypair_path="${DEFAULT_KEYPAIR_PATH}" # the fee payer and authority
blockhash_rpc_url="${DEFAULT_RPC_URL}"
sender_rpc_urls=[
    "${DEFAULT_RPC_URL}"
]