[launcher]
task="close-lookup-table"
jvm_args=["-Xmx512m"]

[config]
keypair_path="${DEFAULT_KEYPAIR_PATH}" # the fee payer and authority

blockhash_rpc_url="${DEFAULT_RPC_URL}" # the rpc used for loading things like blockhash and slot

sender_rpc_urls=[
    "${DEFAULT_RPC_URL}"
]