[launcher]
task="unwrap-wsol"
jvm_args=["-Xmx512m"]

[wrap]
keypair_paths=[
    "${DEFAULT_KEYPAIR_PATH}"
]
blockhash_rpc_url="${DEFAULT_RPC_URL}"
senders=[
    { rpc_url="${DEFAULT_RPC_URL}", skip_preflight=true, max_retries=0 }
]