[launcher]
task="wrap-sol"

[wrap]
keypair_path="/path/to/keypair"
amount_sol=0.1 # amount_lamports is also available
priority_fee_lamports=0 # to avoid accidents, this can only be set in lamports
senders=[
    { rpc_url="your.rpc.url", skip_preflight=true, max_retries=0 }
]